# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-01 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_crminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('campaign_name', models.CharField(max_length=200)),
            ],
        ),
    ]
